spring:
  # datasource config
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://172.22.131.157:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: whb0927
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave:
          url: jdbc:mysql://172.22.131.157:3306/blog_message?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: root
          password: whb0927
          driver-class-name: com.mysql.cj.jdbc.Driver
  # redis config
  redis:
    #redis主机地址(如果你在本地启动就是127.0.0.1，如果在虚拟机就填你虚拟机的地址)
    host: 172.22.131.157
    # Redis服务器端口,默认为6379
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password: whb0927
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
    #连接超时时间ms
    timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
